### ISSUE TITLE
3.14.0 Breaks Isomorphic Applications?

### ISSUE THREAD

**Issue by fozzle** [braintree/braintree-web#290]
### General information

* SDK version: 3.14.0
* Environment: Sandbox
* Browser and OS: N/A (Node) 

### Issue description
Since updating to 3.14.0, importing/requiring the braintree-web sdk in code executed on the server (for isomorphic rendering, for example) results in this error:

```
node_modules/braintree-web/hosted-fields/external/hosted-fields.js:915
module.exports = wrapPromise.wrapPrototype(HostedFields);
                             ^

TypeError: wrapPromise.wrapPrototype is not a function
    at Object.<anonymous> (/Users/kylepetrovich/Code/riff-parse/node_modules/braintree-web/hosted-fields/external/hosted-fields.js:915:30)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kylepetrovich/Code/riff-parse/node_modules/braintree-web/hosted-fields/index.js:4:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kylepetrovich/Code/riff-parse/shared/build/live/components/Payment.js:21:21)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

Reverting to 3.13.0 works.

**Comment by crookedneighbor** [comment]
The dependency for [`wrapPromise`](https://github.com/braintree/wrap-promise) was updated form v1.0.0 to v1.1.0 to include the function `wrapPrototype`. Is it possible that you were somehow able to update `braintree-web` without also updating `wrap-promise`? Have you tried removing your node_modules folder and re-installing everything?

**Comment by crookedneighbor** [comment]
Hmm... it seems like the version on `npm` has the wrong version. We'll look into this.

**Comment by crookedneighbor** [comment]
I have an idea of why this is happening and I've opened an issue on the npm repo: https://github.com/npm/npm/issues/16475

**Comment by crookedneighbor** [comment]
Okay, the problem was that we never bumped the version in the package.json for wrap-promise. So even though `npm` was able to fetch the correct code, based on the git tag, it thought you already had the dep installed since the version number in the package.json was still `1.0.0`.

We've updated the version and re-tagged, so if you re-install, you should be good to go now.

**Comment by fozzle** [comment]
Thank you~

**Comment by mroncka** [comment]
Still having this issue in v2.1.1 when using travis CI
